#!/usr/bin/python3

# sdr console
# ktheis <theis.kurt@gmail.com>
# 4/8/2018
# uses rtl_fm for rx, rpitx for transmit

# this is has a lot of help: http://effbot.org/tkinterbook/

# needs to be run by python3
# needs tkinter (note case!) installed: "sudo apt-get install python3-tk"
# needs rtl_fm installed: "sudo apt-get install rtl-sdr"
# needs sox installed: "sudo apt-get install sox"
# needs to have an rtl dongle installed for the radio hardware

from tkinter import *
# from tkinter.ttk import *   # needed for combobox, screws up everything else
import os

###############
### DEFINES ###
############### 


#############################
########   RX 1   ###########
#############################
 
def rx1ena():	# enable rx 1, change state of disabled buttons
	global RX1FLAG
	rxEna1.config(text="Rx1 Update")
	rxEna1.config(bg="green",fg="black")
	rxEna1.config(activebackground="green",activeforeground="black")
	b1.config(state=NORMAL)
	if RX1FLAG == 1:	# close programs before changing settings
		os.system("killall rtl_fm")
		os.system("killall play")
	cmd = "rtl_fm -M " + mode.get() + " -f " + rxfreq.get() + " -l " + squelch.get() + " -s 22050 -g 40 | play -t raw -r 22050 -e s -b 16 -c 1 -V1 - & "
	print(cmd)
	os.system(cmd)
	RX1FLAG = 1	# enable receiver

def rx1dis():	# disable rx 1, change state of buttons
	global RX1FLAG
	rxEna1.config(text="Rx1 Enable")
	rxEna1.config(bg="black",fg="yellow",activeforeground="yellow",activebackground="black")
	b1.config(state=DISABLED)
	if RX1FLAG == 1:
		os.system("killall rtl_fm")
		os.system("killall play")
	RX1FLAG = 0	# disable receiver

#############################
#######  TX 1  ##############
#############################

def tx1ptt():	# disable rx1, key up tx 1
	global RX1FLAG
	global TX1FLAG

	if TX1FLAG == 0:	# in receive mode - disable rx, enable tx
		if RX1FLAG == 1:	# close programs, restart after keyup
			os.system("killall rtl_fm")
			os.system("killall play")
			RX1FLAG = 2	# 2 means we had a receiver at ptt
			rxEna1.config(bg="yellow",fg="black",activebackground="yellow",activeforeground="black")
			b1.config(state=DISABLED)

		if mode.get() == "fm":	# ptt with nfm
			cmd = "arecord -c1 -r48000 -D plughw:CARD=Device,DEV=0 -fS16_LE - | csdr convert_i16_f | csdr gain_ff 7000 | csdr convert_f_samplerf 20833 | sudo rpitx -i- -m RF -c 1 -f " + txfreq.get() + " & "
			print(cmd)
			os.system(cmd)
		# change buttons to show keyed up state 
		txEna1.config(bg="red",fg="black",activebackground="red",activeforeground="black")
		TX1FLAG = 1	# tx enabled
		return

	if TX1FLAG == 1:	# Already keyed up - unkey, enable receiver
		os.system("sudo killall rpitx")
		os.system("killall csdr")
		os.system("killall arecord")
		txEna1.config(bg="black",fg="yellow",activebackground="black",activeforeground="yellow")
		if RX1FLAG == 2:	# re-enable receiver 1
			b1.config(state=NORMAL)
			rxEna1.config(text="Rx1 Update")
			rxEna1.config(bg="green",fg="black")
			rxEna1.config(activebackground="green",activeforeground="black")
			cmd = "rtl_fm -M " + mode.get() + " -f " + rxfreq.get() + " -l " + squelch.get() + " -s 22050 -g 40 | play -t raw -r 22050 -e s -b 16 -c 1 -V1 - & "
			print(cmd)
			os.system(cmd)
			RX1FLAG = 1	# enable receiver
		TX1FLAG = 0		# disable TX
		return



def rx2ena():	# enable rx 2
	global RX2FLAG

def rx2dis():	# disable rx 2
	global RX2FLAG

def rx3ena():	# enable rx 3
	global RX3FLAG

def rx3dis():	# disable rx 3
	global RX3FLAG

def rx4ena():	# enable rx 4
	global RX4FLAG

def rx4dis():	# disable rx 4
	global RX4FLAG

def rx5ena():	# enable rx 5
	global RX5FLAG

def rx5dis():	# disable rx 5
	global RX5FLAG




####################
### Main Routine ###
#################### 


RX1FLAG = 0
TX1FLAG = 0

RX2FLAG = 0
TX2FLAG = 0

RX3FLAG = 0
TX3FLAG = 0

RX4FLAG = 0
TX4FLAG = 0

RX5FLAG = 0
TX5FLAG = 0

window = Tk()

mode = StringVar()
 
window.title("SDR Console v1.0")
window.geometry('545x350')

### ROW 0 ###
 

### ROW 1 ###

rxEna1 = Button(window,width=10,text="Rx1 Enable",bg="black", fg="yellow",activebackground="black",activeforeground="yellow",height=3,command=rx1ena)
rxEna1.grid(column=1,row=1)

rxEna2 = Button(window,width=10,text="Rx2 Enable",bg="gray",fg="black",state=DISABLED,height=3,command=rx2ena)
rxEna2.grid(column=2,row=1)

rxEna3 = Button(window, width=10, text="Rx3 Enable",bg="gray",fg="black",state=DISABLED,height=3,command=rx3ena)
rxEna3.grid(column=3,row=1)

rxEna4 = Button(window, width=10, text="Rx4 Enable",bg="gray",fg="black",state=DISABLED,height=3,command=rx4ena)
rxEna4.grid(column=4,row=1)

rxEna5 = Button(window, width=10, text="Rx5 Enable",bg="gray",fg="black",state=DISABLED,height=3,command=rx5ena)
rxEna5.grid(column=5,row=1)

### ROW 2 ###

b1 = Button(window,width=10,state=DISABLED,text="Rx1 Disable",command=rx1dis)
b1.grid(column=1,row=2)

b2 = Button(window,width=10,state=DISABLED,text="Rx2 Disable")
b2.grid(column=2,row=2)

b3 = Button(window,width=10,state=DISABLED,text="Rx3 Disable")
b3.grid(column=3,row=2)

b4 = Button(window,width=10,state=DISABLED,text="Rx4 Disable")
b4.grid(column=4,row=2)

b5 = Button(window,width=10,state=DISABLED,text="Rx5 Disable")
b5.grid(column=5,row=2)



### ROW 3 ###

txEna1 = Button(window,width=10,text="Tx PTT 1",height=3,bg="black",fg="yellow",activebackground="black",activeforeground="yellow",command=tx1ptt)
txEna1.grid(column=1,row=3)

txEna2 = Button(window,width=10,text="Tx PTT 2",height=3,state=DISABLED,bg="gray",fg="black")
txEna2.grid(column=2,row=3)

txEna3 = Button(window, width=10, text="Tx PTT 3",height=3,state=DISABLED,bg="gray",fg="black")
txEna3.grid(column=3,row=3)

txEna4 = Button(window, width=10, text="Tx PTT 4",height=3,state=DISABLED,bg="gray",fg="black")
txEna4.grid(column=4,row=3)

txEna5 = Button(window, width=10, text="Tx PTT 5",height=3,state=DISABLED,bg="gray",fg="black")
txEna5.grid(column=5,row=3)


### ROW 4 ###

b6 = Button(window,width=10,state=DISABLED)
b6.grid(column=1,row=4)

b7 = Button(window,width=10,text="RX FREQ",state=NORMAL)
b7.grid(column=2,row=4)

b8 = Button(window,width=10,text="TX FREQ",state=NORMAL)
b8.grid(column=3,row=4)

b9 = Button(window,width=10,state=DISABLED)
b9.grid(column=4,row=4)

b10 = Button(window,width=10,state=DISABLED)
b10.grid(column=5,row=4)



### ROW 5 ###

fLabel = Label(window, text="Frequency ",font=28)
fLabel.grid(column=1,row=5)

rxfreq = Entry(window, width=10,font=28)
rxfreq.delete(0,END)
rxfreq.insert(0,"146.46M")
rxfreq.grid(column=2, row=5)

txfreq = Entry(window, width=10,font=28)
txfreq.delete(0,END)
txfreq.insert(0,"146460")
txfreq.grid(column=3, row=5)

sLabel = Label(window, text="Squelch ", font=28)
sLabel.grid(column=4,row=5)
squelch = Entry(window, width=10,font=28)
squelch.delete(0,END)
squelch.insert(0,"30")
squelch.grid(column=5,row=5)

### ROW 6 ###

mode.set("fm")	# initial conditions

def FMenable():
	mode1.config(bg="beige",fg="black")
	mode2.config(bg="black",fg="yellow")
	mode3.config(bg="black",fg="yellow")
	mode4.config(bg="black",fg="yellow")
	mode5.config(bg="black",fg="yellow")
	mode.set("fm")
mode1 = Button(window,width=10,text="FM",command=FMenable,bg="black",fg="yellow")
mode1.grid(column=1,row=6)

def WFMenable():
	mode1.config(bg="black",fg="yellow")
	mode2.config(bg="beige",fg="black")
	mode3.config(bg="black",fg="yellow")
	mode4.config(bg="black",fg="yellow")
	mode5.config(bg="black",fg="yellow")
	mode.set("wfm")
mode2 = Button(window,width=10,text="WFM",command=WFMenable,bg="black",fg="yellow")
mode2.grid(column=2,row=6)

def AMenable():
	mode1.config(bg="black",fg="yellow")
	mode2.config(bg="black",fg="yellow")
	mode3.config(bg="beige",fg="black")
	mode4.config(bg="black",fg="yellow")
	mode5.config(bg="black",fg="yellow")
	mode.set("am")
mode3 = Button(window,width=10,text="AM",command=AMenable,bg="black",fg="yellow")
mode3.grid(column=3,row=6)

def USBenable():
	mode1.config(bg="black",fg="yellow")
	mode2.config(bg="black",fg="yellow")
	mode3.config(bg="black",fg="yellow")
	mode4.config(bg="beige",fg="black")
	mode5.config(bg="black",fg="yellow")
	mode.set("usb")
mode4 = Button(window,width=10,text="USB",command=USBenable,bg="black",fg="yellow")
mode4.grid(column=4,row=6)

def LSBenable():
	mode1.config(bg="black",fg="yellow")
	mode2.config(bg="black",fg="yellow")
	mode3.config(bg="black",fg="yellow")
	mode4.config(bg="black",fg="yellow")
	mode5.config(bg="beige",fg="black")
	mode.set("lsb")
mode5 = Button(window,width=10,text="LSB",command=LSBenable,bg="black",fg="yellow")
mode5.grid(column=5,row=6)




### Callback ###

window.mainloop()
